sudo: required
services:
  - docker

before_install:
  - docker build -t leel/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=ture leel/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-831926592701"
  bucket_path: "frontend"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
